### ISSUE TITLE
Exception when running composer update

### ISSUE THREAD

**Issue by loevgaard** [symfony/thanks#91]
When I run `composer update` I get the following exception:

```
Writing lock file
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
134 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP Fatal error:  Uncaught Error: Call to undefined method Composer\Util\StreamContextFactory::getTlsDefaults() in /Users/loevgaard/.composer/vendor/composer/composer/src/Composer/Util/HttpDownloader.php:63
Stack trace:
#0 /Users/loevgaard/PhpstormProjects/SyliusMailchimpPlugin/vendor/symfony/thanks/src/GitHubClient.php(103): Composer\Util\HttpDownloader->__construct(Object(Composer\IO\ConsoleIO), Object(Composer\Config))
#1 /Users/loevgaard/PhpstormProjects/SyliusMailchimpPlugin/vendor/symfony/thanks/src/Thanks.php(81): Symfony\Thanks\GitHubClient->__construct(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#2 [internal function]: Symfony\Thanks\Thanks->displayReminder(Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#5 phar: in /Users/loevgaard/.composer/vendor/composer/composer/src/Composer/Util/HttpDownloader.php on line 63

Fatal error: Uncaught Error: Call to undefined method Composer\Util\StreamContextFactory::getTlsDefaults() in /Users/loevgaard/.composer/vendor/composer/composer/src/Composer/Util/HttpDownloader.php:63
Stack trace:
#0 /Users/loevgaard/PhpstormProjects/SyliusMailchimpPlugin/vendor/symfony/thanks/src/GitHubClient.php(103): Composer\Util\HttpDownloader->__construct(Object(Composer\IO\ConsoleIO), Object(Composer\Config))
#1 /Users/loevgaard/PhpstormProjects/SyliusMailchimpPlugin/vendor/symfony/thanks/src/Thanks.php(81): Symfony\Thanks\GitHubClient->__construct(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#2 [internal function]: Symfony\Thanks\Thanks->displayReminder(Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#5 phar: in /Users/loevgaard/.composer/vendor/composer/composer/src/Composer/Util/HttpDownloader.php on line 63
```

My composer version:
```bash
$ composer --version
Composer version 1.10.17 2020-10-30 22:31:58
```

**Comment by nicolas-grekas** [comment]
Hello @loevgaard and thanks for the report.
Unfortunately, I'm not able to reproduce the issue.
This method exists in my vendor/ directory.
Why do you have `composer/composer` in your vendor?
Could this might be the reason, where you have a local composer file that loads classes from both sources (vendor/ and from the composer binary?)

**Comment by loevgaard** [comment]
Thank you, @nicolas-grekas. It was composer-unused package that installed composer in the vendor dir. I removed it and it works.
